### ISSUE TITLE
Sound: Add and improve sounds

### ISSUE THREAD

**Issue by QuentinDaveau** [med-material/Whack_A_Mole_VR#18]
There is currently one sound for mole spawn that needs to be edited to play at the right time (small delay at the start). Modifying the current sound and adding new ones (for mole popped, mole missed) would be nice to improve feedback.

**Comment by bastianilso** [comment]
Agreed. If you have some suggestions (any sounds under a CC-BY or CC-BY-SA is fine) or references, feel free to link/propose them here.

**Comment by QuentinDaveau** [comment]
We could use sounds from websites like [soundbible](http://soundbible.com/), which are open source, or we could even use [BFXR](https://www.bfxr.net/) to make our own, basic custom sounds.

**Comment by hendrikknoche** [comment]
in the previous version of WAM on a tablet we increased the pitch for each successive hit above a certain threshold (e.g. faster than average or some other defined threshold). When this threshold was not passed the sound pitch reset to the basic level.  So that would be with an accumulative effect. The other option would be to assign different pitches or sound effects to different levels of performance for each hit. (e.g. very slow, slow, medium, fast, very fast). 

In either case, the 'speed'  we should actually compute based on performance that is normalized (e.g. that considers the distance travelled) and not a mere constant. It should be based on a per person level (potentially linked with different levels of difficulty (number of distractors).

**Comment by hendrikknoche** [comment]
it should be possible to turn on/off the mole spawning (as it gives you an auditory clue that there should be something). This will also require logging in the log file (one column that denotes whether a mole was visually spawned with an audio sound or not. Maybe we could do this on a per mole basis e.g. add another variable (sound yes/no) per Mole/distractor spawn in #55

**Comment by bastianilso** [comment]
Sound Reference from TrailIT:
https://youtu.be/eDl55mKN9Ug?t=54

Can also look into mahjong, etc. Something neutral.

**Comment by bastianilso** [comment]
oct 7th notes:
- sounds are currently inconsistent/random/delayed.
- it might be nice if we could play different notes depending on which mole is being hit. (so it is a bit like playing a song). but just a nice-to-have idea, lets start with something neutral (this will probably be something to turn on/off).

**Comment by mathiassand** [comment]
Buxton three state model to give an overview of which interactions that can grant the user feedback.

![statemodel WAM audiospace](https://user-images.githubusercontent.com/25637660/95992705-8ce47900-0e2e-11eb-85a3-007349b60ef6.jpg)

**Comment by bastianilso** [comment]
Sounds are now in, since #119
