### ISSUE TITLE
WallManager: Mole states are not reset when game stops

### ISSUE THREAD

**Issue by Xav1204** [med-material/Whack_A_Mole_VR#216]
When we restart a game in the same instance of the app, the last game targets and distractors that are still visible on screen, will stay for the next game but will be shown without their color.
We need to figure out why this is happening. To do this, we probably need to see how the targets and distractors are instantiated at the beginning of the game and also how they are cleaned when we stop a game before its ending.
   
![bug](https://user-images.githubusercontent.com/73820233/194050714-0f6ad3c5-f923-41a4-8e04-545f43abc971.gif)

On this gif, you can see in the red circle the prefabs that are still visible after a new game.

**Comment by bastianilso** [comment]
Thanks for reporting @Xav1204 . I changed the title from
 "_Game Bug : Target and Distractor Prefab_"
 to
 _WallManager: Mole states are not reset when game stops_ 

This is because we try to follow a convention in the issue tracker, it looks like this:

```
<Location of the problem>: <Problem explained>
```

The idea behind the convention is that it makes it easy to skim-read the list of issues, and understand both the problem in short and the location of it. If we want to highlight this as a bug, we can put a label on the issue named "bug".

Consider this for future issues. Hope the explanation made sense, let me know if you have questions.

And feel free to work on this bug if you want, by the way. 🙂👍

**Comment by lucasmnt** [comment]
Little update here : I fixed the bug and made a pull request :)
