### ISSUE TITLE
UI: Add Profile UI

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#27]
With the connection to the MySQL server issue #5 , we need basic identification of users. In Trail it, we do this by giving people the ability to create simple profiles consisting of a name and an e-mail address.
The following mockups show a basic UI which could be intergrated into Whack-A-Mole VR.
Internally to keep implementation simple, I suggest the profiles are stored using PlayerPrefs, Unity's built-in player preferences system. See the Trail it implementation, for reference [SettingsScreen.LoadSettings()](https://github.com/med-material/Trail-it/blob/master/Assets/Scripts/SettingsScreen.cs#L180).

![whack-create-profile](https://user-images.githubusercontent.com/3967945/68189435-8bb69500-ffab-11e9-92c9-9a938f5ffa5d.png)
![whack-profile-selection](https://user-images.githubusercontent.com/3967945/68189438-8d805880-ffab-11e9-8f5a-7b95dc95fbc3.png)
 
(Edit: Added GDPR Data clause)

**Comment by bastianilso** [comment]
Some behavior remarks:

- When no profiles are present, hide that part of the UI.
- If any profiles are loaded, show them as buttons, which can be quickly selected.
- When a profile is selected or created, the regular Whack-A-Mole Therapist Main Menu UI is shown.

I have not designed anything for the minimized state of the UI, for the time being.

**Comment by bastianilso** [comment]
Assets used in the mockup:
[profile-ui-assets.zip](https://github.com/med-material/Whack_A_Mole_VR/files/3803699/profile-ui-assets.zip)

**Comment by QuentinDaveau** [comment]
@bastianilso From what I understood by having a look at Trail-it's code, the profiles are stored locally. Since we are working in close relation with the database, shouldn't we instead store them in the form of a table in the database ? This may make more sens considering #38, where the config files are stored online.

I also think that, since this issue and #38 seems to be closely linked, we should consider them altogether for the desing of the UI, this may facilitate their implementation/design on the long term.

What do you think about all of this ?

**Comment by bastianilso** [comment]
@QuentinDaveau yes, the profiles and settings are stored locally in Trail it.

I agree that it would be nice to have the profiles in the database, but it does open up its own can of worms:
- The current ConnectToMySQL package was not designed for this, so you'll end up with a custom implementation or a hack (fx allowing to pass a table name to `AddToUploadQueue`).
- We would need to handle what to do if offline.
- Profiles would need to be synchronized as settings are changed.
- Ideally we talk to the profile table using the same PHP backend as ConnectToMySQL.
- We eventually get very close to a profile system / sign-in system. Then we would need to handle passwords, resetting passwords which might mean sending out e-mail notifications.

From our own experiment point of view, we are not necessarily interested in this:
- When people switch to using Whack-A-Mole on a different system, many variables change in terms of the system's properties (VR type, system performance etc) anyway, which makes the data difficult to compare. So we usually treat these as separate experiments anyway - perhaps with a single identifier (fx e-mail address), which makes it possible to compare.
- Online Sign-in systems require people to have passwords..this is just yet another barrier, especially given our target group (stroke patients who have partial brain bleeding).

So for time being, I think an offline profile system like the one in Trail it will make do as the initial implementation. We might then solve #38 through a different means - I will need to think about that. For #38 it could be something simple to start with like being able to export the set of profiles to a file, which is then loaded from Ressources/ (or from a server)? Anyway, lets discuss that in #38.

**Comment by QuentinDaveau** [comment]
@bastianilso Is selecting a profile mandatory for playing the game ? If that's the case the minimize tray wouldn't be needed, we could just display the profile window at the beginning (with a default profile if no custom profile exists), and force the therapist to select a profile. Also, should we add a button somewhere on the therapist panel to change the current profile ? We may want to add it on another panel though, otherwise the therapist panel may get quite crammed.

**Comment by bastianilso** [comment]
@QuentinDaveau lets keep the minimize tray there for consistency sake. yes, profile selection is mandatory on startup.

as for how to get out of profile selection, how about we initially make something like this?
![image](https://user-images.githubusercontent.com/3967945/70538661-c4c1c680-1b62-11ea-8df6-8af511e31870.png)

true that the therapist panel is crammed - I want to move our modifers into a slightly more compact layout eventually.

**Comment by QuentinDaveau** [comment]
@bastianilso Okay, so if I inderstood corresctly, the case of use would be:

- On startup, the profile selection panel appears without any way to bypass it. The therapist is forced to either select a profile, or create one.
- The therapist selects/creates a profile. The profile panel disappears and the usual therapist panel is shown.
- If the therapist wants to change profile, he can click on the new profile button on the top left of the therapist panel to come back to the profiles panel.

This raises a few questions:

 - How should we manage the case of someone who doesn't want to use any profile (for example to do some random tests without polluting a given profile) ? Should there be a "default" profile ? Or should we allow to bypass the profile panel (with a "don't use a profile" button) ?

 - We may want to allow the user to delete a given profile (maybe we can add a "delete" button on the right of the profile button, which would need to be double clicked to delete the profile or ask through a pop-up if the user is sure he wants to delete the profile).

 - We may want to disable the "change profile" button when the game is running. Otherwise this may cause some issues.

What are your thoughts on these ?

**Comment by QuentinDaveau** [comment]
A few more questions:

 - Should we allow multiple profiles with the same email / name ? It would make sens to have multiple time the same mail in some cases since the therapist may want to create multiple profiles with his mail. However I think the name should be unique.

 - Should the profile be logged in the database ? If yes, should we ensure that each profile has a unique ID, whatever the computer they're from ?

**Comment by bastianilso** [comment]
> How should we manage the case of someone who doesn't want to use any profile (for example to do some random tests without polluting a given profile) ? Should there be a "default" profile ? Or should we allow to bypass the profile panel (with a "don't use a profile" button) ?

To keep things simple, I would force profile creation. - any random tests and such can be done on a testing profile.

> We may want to allow the user to delete a given profile (maybe we can add a "delete" button on the right of the profile button, which would need to be double clicked to delete the profile or ask through a pop-up if the user is sure he wants to delete the profile).

Good point, here is a mockup for that:
![profie-deletion](https://user-images.githubusercontent.com/3967945/70979998-d8b17f00-20b2-11ea-8108-ed2adea8a225.png)

Some comments:
- If we have a surplus of profiles causing the content to dissapear towards the bottom, we could make the UI pannel a Scrollable UI or create a grid of profile buttons.
- The "Delete Profile" becomes a button on hover.
- When a profile has been selected for deletion, the panel returns to the profile selection panel. The assumption is that people typically just need to delete a single profile (also that this is a very uncommon action).
- The third image is optional - but to be friendly we should allow people to undo their action (ie. the profile(s) is simply scheduled for deletion and will be deleted once a different profile is selected).
- In the implementation, could we keep profiles represented as physical text files on the computer? This would take care of the researcher case, where we want to create profiles with predetermined settings for experimentation.

> We may want to disable the "change profile" button when the game is running. Otherwise this may cause some issues.

My suggestion is to keep the change profile button pressable, but to stop the game when the button is pressed.

> Should we allow multiple profiles with the same email / name ? It would make sens to have multiple time the same mail in some cases since the therapist may want to create multiple profiles with his mail. However I think the name should be unique.

We should allow people to do that and use a unique profileID in the backend to distinguish profiles from each other. Maybe we can be nice and add a number next to it automatically. Ie. "Quentin" and "Quentin 2"

> Should the profile be logged in the database ? If yes, should we ensure that each profile has a unique ID, whatever the computer they're from ?

Yes, good idea. ⭐️ In Trail it, we used an [MD5 hash of the name, email and system.DateTime.Now](https://github.com/med-material/Trail-it/blob/master/Assets/ProfileManager.cs#L137) which I doubt will ever create collisions since its taking milliseconds into account.

**Comment by bastianilso** [comment]
icon used in delete profile mockup:
[x.zip](https://github.com/med-material/Whack_A_Mole_VR/files/3972381/x.zip)

**Comment by QuentinDaveau** [comment]
@bastianilso thanks for the precisions. Just one small question though:

> In the implementation, could we keep profiles represented as physical text files on the computer? This would take care of the researcher case, where we want to create profiles with predetermined settings for experimentation.

This would mean that we no longer use Unity's PlayerPref. If you are referencing #38, we may want to consider it apart, since in #38 we are speaking about "test profile" where here we are speaking about "user profile". I agree that a file (like a CSV) would be better, since this would also mean that the Therapist can copy a profile from a computer to another, which could prove useful in some cases (maybe in a distant future where there are many different parameters that can be tweaked).

What are your thought on this ?

**Comment by bastianilso** [comment]
@QuentinDaveau I'm fine with using files stored on disk instead of playerpref. I think we will leave #38 open for the purpose of generating specific profiles based on retreiving data from a table in the db.

I would use CSV or a *.ini style file which is easy to edit in a text editor.

**Comment by QuentinDaveau** [comment]
@bastianilso Ok. I'll try to implement it in the *.ini format since it is really easy to edit

**Comment by QuentinDaveau** [comment]
@bastianilso could you give the ressource for the profile icon on the therapist UI ?

![image](https://user-images.githubusercontent.com/45624296/71169474-4697ab00-2259-11ea-9800-6a8b6a52fc04.png)

**Comment by bastianilso** [comment]
> @bastianilso could you give the ressource for the profile icon on the therapist UI ?

Woops, missed it, here you go:
[profile-icon.zip](https://github.com/med-material/Whack_A_Mole_VR/files/3983473/profile-icon.zip)

**Comment by QuentinDaveau** [comment]
Many thanks !

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of #53. Closing the issue.
