### ISSUE TITLE
Send participant test logs to MySQL database

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#5]
- [x] Create a table to store data from VR Whack-a-mole on our CREATE Server.
- [x] Integrate the [ConnectToMySQL package](https://github.com/med-material/ConnectToMySQL) with Whack-a-mole's logger.

If the data we log from Whack-a-mole is real-time, we may want to look into either 1) sending only data aggregates to the server or 2) logging the data locally and sending the data by the end of the session to the server.

**Comment by QuentinDaveau** [comment]
Should the logger still save the data as a CSV file as well or not ? Maybe we can add it as an option ?

**Comment by hendrikknoche** [comment]
I think it would be good to have this as an option that by default is on. This will help the people who either have no access to the database or do not know how to handle it.

**Comment by QuentinDaveau** [comment]
It is required to give the connectToMySQL package an Email field in the logs to save, otherwise it won't save the logs. However the Therapist UI currently doesn't integrate an Email field. Should we add it, maybe with the "participant id" and "Test id" fields ?

**Comment by QuentinDaveau** [comment]
> I think it would be good to have this as an option that by default is on. This will help the people who either have no access to the database or do not know how to handle it.

> It is required to give the connectToMySQL package an Email field in the logs to save, otherwise it won't save the logs. However the Therapist UI currently doesn't integrate an Email field. Should we add it, maybe with the "participant id" and "Test id" fields ?

Maybe we should put these options on another UI element instead of the current Therapist UI, otherwise it may be a bit too dense, with many options which differs too much in purpose and uses.

**Comment by hendrikknoche** [comment]
could you post the current screen shot to make it easy to discuss here in the thread?

**Comment by QuentinDaveau** [comment]
> could you post the current screen shot to make it easy to discuss here in the thread?

Currently the UI looks like this:

![image](https://user-images.githubusercontent.com/45624296/68114920-7f710000-fef7-11e9-9c0b-9356942b38a6.png)

Its main purpose is to set-up the game. Options for the logging may be a bit out of context seen the current options' purpose, and the UI may become quite dense. We may also want to keep some free space if we want to add more game options in the future (like #13)

**Comment by bastianilso** [comment]
@QuentinDaveau I have added some basic mockups for solving the UI-side of this, see issue #27.

**Comment by QuentinDaveau** [comment]
@bastianilso I seem to have some issues sending data to the database through the ConnectToSQL unity package. The headers and data passed to the package seems fine. I suspect the issue to be between the PHP script and the database, however I have no way to verify it since I don't have access to the PHP script. I think having to the SQL logs on phpmyadmin or even better, having a copy of the php script, would really help. Would that be possible ?

**Comment by bastianilso** [comment]
@QuentinDaveau few things first:

- Could you post the debug info given by ConnectToMySQL in the Unity console? 
- Could you list to me the columns in your database table, and the corresponding columns you are trying to send?
- If you are still at the stage of trying to send all the data, I suggest you try instead with a small test first, and scale up from there (e.g. sending only 3 columns). Sometimes certain column names might cause issues. 

I'll see what I can do about providing the php script - but this is closed infrastructure, so for the time being, treat this as black box debugging exercise. (proprietary software yay.....) :b

**Comment by QuentinDaveau** [comment]
The error I get is a 500 internal error: "Failed to insert data into the database. Check that column names are correct and the data corresponds.". However this doesn't obviously mean that the issue comes from the inserted datas. I also have the same error if I put a non existent database name of table name. There are 88 columns (so quite a bit), so I won't list them here but you can see them on the database if you need to. I will try to create a dull table and send only a few datas, I'll keep you in touch of the result.

**Comment by QuentinDaveau** [comment]
I suppose the issue could also come from the format of the columns in the SQL database (char, float...). What is weird is that if I try to insert the same values sent from the Unity package to the PHP script by hand (importing them as CSV through PHPmyadmin), it works perfectly fine.

**Comment by bastianilso** [comment]
@QuentinDaveau typically this error means that:

- ConnectToMySQL managed to find the php script
- it managed to establish connection to the database and log in, using your provided credentials successfully.
- it managed to locate the database
- it managed to locate the table
- it managed to identify that your user has the adequate rights to `INSERT` into the table

..however, when sending the `INSERT` statement, the MySQL database rejected the data.

Let me know whether you manage to send a small amount of data. I think this might be a good way to debug which exact columns are causing troubles.

**Comment by bastianilso** [comment]
@QuentinDaveau another thing I suggest you check, is that each list in the data structure you are sending contains the same number of elements. (ie. if TimeStamp column contains 98 entries, but another contains 95, then we might get in trouble)

**Comment by QuentinDaveau** [comment]
> @QuentinDaveau another thing I suggest you check, is that each list in the data structure you are sending contains the same number of elements. (ie. if TimeStamp column contains 98 entries, but another contains 95, then we might get in trouble)

First thing I checked actually, and they do contain the same number of elements. So I don't think the issue comes from here. The test with a small database should give us more insight.

**Comment by QuentinDaveau** [comment]
@bastianilso small question, does the Email address field in the ConnectToMySQL Unity package has any important meaning or not (is this value used in any way) ?

**Comment by bastianilso** [comment]
@QuentinDaveau it is not used, from what I can see in the ConnectToMySQL code. Could you file a bug against the Unity Package about that?

**Comment by QuentinDaveau** [comment]
@bastianilso 

> Could you file a bug against the ConnectToMySQL Unity Package about that?

okay, I'll create an issue. I also would like to create an issue to add more documentation (maybe an example Unity project, samples...), is-that okay with you ?

Concerning the test with a small database, I seem to have the same issue. However if I change the format of each field as varchar, it does work. I suppose the issue may come from a format conflict, I'll try to see if that's the case.

**Comment by QuentinDaveau** [comment]
@bastianilso, I found the source of the issue. The issue does come from the formats of the columns. It seems that when we pass a "NULL" value to the PHP script, it saves it as a "NULL" string. Meaning that if we have a column declared as float, it tries to set it as a "NULL" string, causing the error.

This may be an issue. We can either:

- Do as planned originally and let the database set the default value (the NULL value), which is not the best since it would mean that the datas would be controlled by two distinct entities, the Unity game AND the SQL database;

 - Define a default value for any float/int, which would not be a very good solution since it would mean having "noise values" to take into account and to ignore when doing data analysis;

 - Try to find a way to tell the PHP script to send a NULL value, which, to me, would be the cleanest and best solution (it could support such functionality, maybe through certain fields/headers, this is where having access to the PHP script would be useful).

**Comment by QuentinDaveau** [comment]
Actually, if we make sure that every column of the database has its default value set as NULL and that it won't be changed in the furure (for any reason), we can simply apply the idea 1:

> Do as planned originally and let the database set the default value (the NULL value), which is not the best since it would mean that the datas would be controlled by two distinct entities, the Unity game AND the SQL database;

However we really have to make sure that it won't be changed. And, in any case, I think the idea 3 may be the cleanest (if it is possible to do it).

**Comment by bastianilso** [comment]
@QuentinDaveau good idea to also have a small example Unity project in the ConnectToMySQL package. If you feel like it, maybe having a small testscene available in that Unity project and a corresponding test_table in the db, would be good?

I have a possible update to the PHP script which might fix using 3), but will need to wait for our IT infrastructure to renew my permissions to access the server.

**Comment by QuentinDaveau** [comment]
Created some issues to the [ConnectToMySQL repo](https://github.com/med-material/ConnectToMySQL).

**Comment by QuentinDaveau** [comment]
Issue fixed in branch merging #30. Closing the issue.
