### ISSUE TITLE
Disable / Decrease Sensitivity of Controller Rotation

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#51]
In stroke rehabilitation patients typically have a healthy side ( typically right) and a paralyzed "neglected side" (typically left). For the purpose of stroke rehabilitation, patients will need to practice moving their healthy arm into their "neglected side." Currently, Whack-A-Mole VR can be played without moving your arm at all - you can simply rotate the controller with your hand.

To encourage patients to use their whole arm we should decrease the sensitivity of the controller or completely disable the rotational aspect of the controller - instead patients should point on the moles by moving their arm.

**Comment by QuentinDaveau** [comment]
@bastianilso I think this would need careful design to work. Reducing the Pointer sensivity would feel unintuitive, and disabling the pointer rotation would mean greatly reducing the wall size so the participant can hit every Mole (this may be in conflict with the idea that the whole Participant's field of view is covered by the wall). On the practical aspect I don't think this would really work, I can quickly implement it so we can test them, but I think we may want to try to find a better solution.

Could you give a bit more context on what the end goal is so we can to discuss the implementation more easily ?

**Comment by hendrikknoche** [comment]
yes, indeed this is a tricky one. But for upper limb rehabilitation and specifically the problem that some patients have a reduced motor space (in which they can move the controller) we need to be able to: 
1. establish their motor control region (in 3D space). 
2. change the control-display gain accordingly such that we don't have to reduce the size of the display field which we need for diagnostics of e.g. neglect.
3. establish what are the smallest targets they can reliably and with ordinary effort acquire
this could both apply to rotation and translation of the controller (but we should be able to control that independently).
In case anyone is interested here's a student paper excerpt that looked into manipulating the CD gain (to increase of motion for people with neck pain) and specifically details previous work on the topic of fiddling with CD gain (in this case on head rotation (not the controllers) but we could assume that results would be similar).


Control-Display (C-D) Gain in 3D, a concept by Poupyrev et al.[10]
is the ratio between a person’s head rotation and the virtual rotation
on the display. Unity (1.0 or 0%) Gain is when the virtual movement
is in sync with the head movement. Positive Gain means the virtual
movement is increased compared to the head movement, while
Negative gain means the virtual rotation is decreased. For a 10%
or 1.1 gain, a 30◦ head rotation would mean a 33◦ virtual rotation.
A -10% or 0.9 gain on the same 30◦ head rotation would mean a
27◦ virtual rotation. Since the mapping is relative, one point in 3D
space will always be the same as the one in real life regardless of
C-D gain, this point is when the user is looking in the "forward"
direction set up in the program, with their heads level with the
ground.
Multiple experiments have been done regarding C-D gain, especially
about finding the Just Noticeable Difference (JND). JND is
the C-D gain where a participant cannot tell the difference between
the virtual, and real movements. Chen et al. [2] and Harvie et al.
[6] both investigated JND, and came to similar conclusions. The
primary measure in both experiments was gain detection, while
C-D gain was manipulated between 0.6 and 1.5. The method for
getting the JND was different, as Chen et al. used Steinicke et al.’s
[12] research to use a Detection Threshold (DT) at a 25%, meaning
that the C-D gain where 25% of the participants notice the difference
between unity and the altered C-D gain is the JND gain. Each
participant had to go through C-D gains from 0.7 to 1.5 with a 0.1
step and perform 4 neck rotations at 55◦ left and right. Harvie et
al. on the other hand used C-D gains from 0.6 to 1.3 with a step of
0.02, their 9 participants had to perform neck rotations, however it
was not mentioned how many per C-D gain step, or the degree of
rotations. Instead of using a fixed DT, they chose the JND gains as
the two extreme values where participants identified the unity and
altered C-D gains as identical. The positive JND gain was similar in
both experiments, Chen et al.’s being 1.159 and Harvie et al.’s 1.18,
however on the negative C-D gain, it was 0.903 and 0.72 respectively.
A possible reason for this can be Harvie et al.’s method for
identifying the JND. The two extremes were detected as identical
in about 46% of the time, meaning that on these two C-D gains, 54%
found it different - an arbitary DT, which is more than double than
the DT used by Chen et al.
Both Chen et al. [3] and Harvie et al. [6, 7] revisited their results
in later experiments. Both looked into the application of C-D gain
on neck pain patients, with different approaches. Harvie et al. [6]
used their findings on JND as upper and lower boundaries in their
experiment on 24 neck pain patients whether C-D gain has an effect
on their Pain Free Range of Motion (PfROM), the angles of neck
rotation when acute pain sets in. With the C-D gains 0.8, 1.0 and 1.2,
they asked the participants to rotate their heads six times left and
right until they feel pain. They found that at 0.8 gain the PfROM
increased by 6% and at 1.2 it decreased by 7% compared to unity
gain, and that the C-D gain had no effect on their average pain.
Chen et al.[3] used a similar method to their previous experiment,
this time with 9 neck pain patients, with a C-D gain ranging from
0.8 to 1.0 with a step of 0.05. The participants did not have to go
over C-D gains of 1.0 as they would not rotate their heads over
their demonstrated limits, which is in accordance to the findings of
Harvey et al. [6]. The average JND Gain of the neck pain patients
was at 0.95 C-D gain compared to the 0.903 of healthy people, suggesting
that neck pain patients notice the difference in C-D gains
before healthy people, which contradicts the findings of Harvie et al.
[7], who, in a similar setup, with gains ranging from 0.6 to 1.4 was
testing whether healthy or neck pain patients noticed altered visual
feedback. They measured gain detection and scored it based on
whether the answer was correct, and found that neck pain patients
scored lower than healthy people. In their final experiment, Chen
et al. [3] used the individual JND for each of their participants, and
calculated a "nudged" gain, which was 0.5 less than their personal
JND gain. They then asked the participants to perform the same
looking exercise. The measures in the evaluation task were verbal,
and patients at nudge Gain said that the neck movement was "feasible
and as expected". As they only used negative C-D gains for
this experiment, the results correlate again with Harvie et al.’s [6]
findings. Chen et al. theorize that for sitting experiments a higher
than 25% DT is possible, such as the one determined by Harvie et
al. [6], and they note that the JND Gains are highly individual, and
may not be applicable for other movements.

references
[1] Benjamin Bolte, Marc de Lussanet, and Markus Lappe. 2016. Virtual reality system
for the enhancement of mobility in patients with chronic back pain. International
Journal of Child Health and Human Development 9, 3 (2016), 305. https://search.
proquest.com/docview/1850780073?rfr_id=info%3Axri%2Fsid%3Aprimo
[2] Karen B. Chen, Kevin Ponto, Mary E. Sesto, and Robert G. Radwin. 2014. Influence
of altered visual feedback on neck movement for a virtual reality rehabilitative
system. Proceedings of the Human Factors and Ergonomics Society Annual Meeting
58, 1 (Sept. 2014), 693–697. https://doi.org/10.1177/1541931214581162
[3] K. B. Chen, M. E. Sesto, K. Ponto, J. Leonard, A. Mason, G. Vanderheiden, J.
Williams, and R. G. Radwin. 2017. Use of Virtual Reality Feedback for Patients
with Chronic Neck Pain and Kinesiophobia. IEEE Transactions on Neural Systems
and Rehabilitation Engineering 25, 8 (Aug. 2017), 1240–1248. https://doi.org/10.
1109/TNSRE.2016.2621886
[4] Seneth Gajasinghe, Mandika Wijayaratna, and Anuja Abayadeera. 2010. Correlation
between numerical rating scale (NRS) and visual analogue scale (VAS) in
assessment of pain in post operative patients. Sri Lankan Journal of Anaesthesiology
18, 2 (Nov. 2010), 81–83. https://doi.org/10.4038/slja.v18i2.2445
[5] Jan Hartvigsen, Mark J Hancock, Alice Kongsted, Quinette Louw, Manuela L
Ferreira, StÃľphane Genevay, Damian Hoy, Jaro Karppinen, Glenn Pransky,
Joachim Sieper, Rob J Smeets, Martin Underwood, Rachelle Buchbinder, Jan
Hartvigsen, Dan Cherkin, Nadine E Foster, Chris G Maher, Martin Underwood,
Maurits van Tulder, Johannes R Anema, Roger Chou, Stephen P Cohen,
LucÃŋola Menezes Costa, Peter Croft, Manuela Ferreira, Paulo H Ferreira,
Julie M Fritz, StÃľphane Genevay, Douglas P Gross, Mark J Hancock, Damian
Hoy, Jaro Karppinen, Bart W Koes, Alice Kongsted, Quinette Louw, Birgitta
ÃŰberg, Wilco C Peul, Glenn Pransky, Mark Schoene, Joachim Sieper, Rob J
Smeets, Judith A Turner, and Anthony Woolf. 2018. What low back pain is and
why we need to pay attention. The Lancet 391, 10137 (June 2018), 2356–2367.
https://doi.org/10.1016/S0140-6736(18)30480-X
[6] Daniel S. Harvie, Markus Broecker, Ross T. Smith, Ann Meulders, Victoria J.
Madden, and G. Lorimer Moseley. 2015. Bogus Visual Feedback Alters Onset of
Movement-Evoked Pain in People With Neck Pain. Psychological Science 26, 4
(April 2015), 385–392. https://doi.org/10.1177/0956797614563339
[7] Daniel S. Harvie, Susan Hillier, Victoria J. Madden, Ross T. Smith, Markus
Broecker, Ann Meulders, and G. Lorimer Moseley. 2016. Neck Pain and Proprioception
Revisited Using the Proprioception Incongruence Detection Test.
Physical Therapy 96, 5 (May 2016), 671–678. https://doi.org/10.2522/ptj.20150210
[8] Marianne Jensen Hjermstad, Peter M. Fayers, Dagny F. Haugen, Augusto Caraceni,
Geoffrey W. Hanks, Jon H. Loge, Robin Fainsinger, Nina Aass, Stein Kaasa, and
European Palliative Care Research Collaborative (EPCRC). 2011. Studies comparing
Numerical Rating Scales, Verbal Rating Scales, and Visual Analogue
Scales for assessment of pain intensity in adults: a systematic literature review.
Journal of Pain and Symptom Management 41, 6 (June 2011), 1073–1093.
https://doi.org/10.1016/j.jpainsymman.2010.08.016
[9] Ted Jones, Todd Moore, and James Choo. 2016. The Impact of Virtual Reality on
Chronic Pain. PLOS ONE 11, 12 (Dec. 2016), e0167523. https://doi.org/10.1371/
journal.pone.0167523
[10] Ivan Poupyrev, Suzanne Weghorst, Takahiro Otsuka, and Tadao Ichikawa. 1999.
Amplifying Spatial Rotations in 3D Interfaces. In CHI ’99 Extended Abstracts on
Human Factors in Computing Systems (CHI EA ’99). ACM, New York, NY, USA,
256–257. https://doi.org/10.1145/632716.632874
[11] K. M. Refshauge and C. G. Maher. 2006. Low back pain investigations and
prognosis: a review. British Journal of Sports Medicine 40, 6 (June 2006), 494–498.
https://doi.org/10.1136/bjsm.2004.016659
[12] Frank Steinicke, Gerd Bruder, Jason Jerald, Harald Frenz, and Markus Lappe.
2008. Analyses of human sensitivity to redirected walking. In Proceedings of the
2008 ACM symposium on Virtual reality software and technology - VRST ’08. ACM
Press, Bordeaux, France, 149. https://doi.org/10.1145/1450579.1450611
[13] E. Taal, M. M. Veehof, and M. A. van de Laar. 2013. THU0482-HPR Comparison
of agreement and responsiveness to treatment effects of 100 mm visual analog
scale and 11 point numerical rating scale to assess wrist pain in patients with
rheumatoid arthritis. Annals of the Rheumatic Diseases 71, Suppl 3 (June 2013),
741–741. https://doi.org/10.1136/annrheumdis-2012-eular.2447
[14] Gul Deniz Yilmaz Yelvar, Yasemin ÃĞÄśrak, Murat DalkÄślÄśnÃğ, Yasemin
Parlak Demir, Zeynep Guner, and AyÅ§enur Boydak. 2017. Is physiotherapy integrated
virtual walking effective on pain, function, and kinesiophobia in patients
with non-specific low-back pain? Randomised controlled trial. European Spine
Journal 26, 2 (Feb. 2017), 538–545. https://doi.org/10.1007/s00586-016-4892-7

**Comment by bastianilso** [comment]
@QuentinDaveau I see what you mean with the unintuitiveness part, very good point. One way this could be resolved is if we add a different "explanation source" for the laser. For instance a shield-like circular object which follows the controllers location, but is unaffected by the controller's rotation. I think this way we get the best of both worlds - 1) people have 1-1 mapping between what they hold and what they see, and 2) we also get a nice explanation for where this laser is coming from, and get the correct "clinical behavior". 👨‍⚕ 

![image](https://user-images.githubusercontent.com/3967945/71175142-1820cc80-2267-11ea-9541-42e0960e8663.png)
