### ISSUE TITLE
mole hit size and rotation DOFs needed for FittsLaw modeling

### ISSUE THREAD

**Issue by hendrikknoche** [med-material/Whack_A_Mole_VR#76]
To model the interaction data with Fitts law (just like in TunnelGoalFitts) we need the size of the mole logged in the same units e.g. cm, or unity units as the distance between moles (i.e. what we log in the last x/y position). Given that we can simply use rotation for pointing we should also articulate both the size of the mole and the previous position in terms of degrees.
I assume the total rotation would be the combined rotation (the equivalent of pythogoras) in terms of yaw (x) and pitch (y). Most likely the latter will yield better/more appropriate data.

**Comment by bastianilso** [comment]
Commit 5245a73c601b20d6fd78efecfd289cecde565795 adds a `MoleSize` (diameter) column, measured in Unity World Coordinates. This is measured based on the rendered size - I assume this can differ based on where the mole is (because the wall bends slightly). But we would need to check if the size is a valid/usefully expressed in its current state.

I don't know whether we want to address rotation for pointing in degree space as you suggest, or whether we should disable pointing (and thus only rely on arm movement). Perhaps from the current logs we gather, do we have enough information to calculate degrees in R?

**Comment by hendrikknoche** [comment]
hmm, if we know size of the mole in the same units as the distance from controller to mole then yes, we have all we need to calculate it in R.
